services:
  postgresql:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=course_archive_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - dev

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    depends_on:
      - postgresql
    profiles:
      - dev

  postgresql_preview:
    image: postgres:16.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=course_archive_preview_db
    networks:
      - preview-network
    profiles:
      - preview
  backend_spring_preview:
    build:
      context: ./backend
      dockerfile: Dockerfile.preview
    ports:
      - 8080:8080
    depends_on:
      - postgresql_preview
    networks:
      - preview-network
    profiles:
      - preview
  frontend-preview:
    build:
      context: ./frontend
      dockerfile: Dockerfile.preview
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - preview

networks:
  preview-network:
    driver: bridge
volumes:
  postgres-data:
