FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src

COPY src/main/resources/preview/uploads-data ./backend/uploads

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.arguments=--spring.profiles.active=preview"]
