INSERT INTO role (name) SELECT 'ROLE_USER' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='ROLE_USER');
INSERT INTO role (name) SELECT 'ROLE_MANAGER' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='ROLE_MANAGER');
INSERT INTO role (name) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='ROLE_ADMIN');